### ISSUE TITLE
Support JSS v.8.0.0

### ISSUE THREAD

**Issue by visioncan** [cssinjs/react-jss#104]
I had custom setup:
```js
import {create as createJss} from 'jss' // v8.0.0
import {create as createInjectSheet} from 'react-jss'
...
export const injectSheet = createInjectSheet(jss)
``` 
the style sheet render not correctly.

result : 
```css
somestyle {
    transition: [object Object];
}
```
thanks!!
