### ISSUE TITLE
Accessing props in psuedo :nth-child()

### ISSUE THREAD

**Issue by janhartmann** [cssinjs/react-jss#158]
I am trying to create a grid component, where I would like to create the following styles:

```css
div {
  width: calc(99.9% * 1/3 - (30px - 30px * 1/3));
}
div:nth-child(1n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
div:last-child {
  margin-right: 0;
}
div:nth-child(3n) {
  margin-right: 0;
  float: right;
}
div:nth-child(3n + 1) {
  clear: both;
}
```
I have a component accepting `props.fraction` (1/3),  `props.gutter` (30px). My initial approach was to do something along the lines of:

```js
const styles = theme => ({
     grid: {
        "& div": {
            width: props =>`calc(99.9% * ${props.fraction} - (${props.gutter} - ${props.gutter} * ${props.fraction}))`
        },
        "& div:nth-child(1n)": {
            float: "left",
            marginRight: props => props.gutter,
            clear: "none"
        },
        "& div:last-child": {
            marginRight: 0
        },
        "& div:nth-child(3n)": { // But here I need to access my props.fraction
            marginRight: 0,
            float: "right"
        },
        "& div:nth-child(3n + 1)": { // Also here
            clear: "both"
        }
    }
});
```

It would be cool if the `injectSheet(styles)(Component)` could inject the props as a second argument.
